KAN-78 feat: 블로그 리뷰 페이지 구현
kakaotech-bootcamp-22/fe pull request #10
Opened 2024-12-02 10:10 UTC by sall6550

### 🔗 관련 이슈
[KAN-78](https://ktb-22.atlassian.net/browse/KAN-78
)

### 📌 작업 내용
- 페이지네이션 구현
- 하트 클릭 백엔드 API 연결
- 블로그 후기 등록API 연결
- 프로필 이미지 크기 조정
- 블로그 리뷰 및 별점 통계 조회 기능 추가

### 🧑‍💻 작업 유형
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] CI/CD 변경

### 📷 관련 이미지
<img width="1330" alt="image" src="https://github.com/user-attachments/assets/745cbe3a-4c21-411e-863c-809751dd3c33">

### 🚨 주의 사항

### ✅ 체크 리스트
- [ ] 코드 리뷰어가 이해할 수 있도록 주석 및 설명을 추가했습니다.
- [ ] 테스트를 추가하거나 업데이트했습니다.
- [ ] 문서를 업데이트했습니다 (해당 시).
- [ ] 이 변경 사항이 다른 기능에 영향을 미치는지 확인했습니다.

2024-12-03 10:20 UTC, dayaelee requested changes

2024-12-03 10:20 UTC, dayaelee commented on src/pages/Review/Review.jsx
> +            <button
최초 하트 클릭전에는 빈하트로 표시하는게 사용자가 이미 하트 클릭한 후기인지 아닌지 인지하는데 좀 더 유용할 것 같아보입니다! (다른 사이트의 후기 시스템의 페이지에는 그런식으로 처리되는 곳이 대부분이였긴 했습니다! (개인적 경험))

2024-12-03 10:20 UTC, dayaelee commented on src/pages/Review/Review.jsx
> +      alert("리뷰가 등록되었습니다!");
리뷰 등록후 입력 필드를 비우는 로직 추가가 필요해 보입니다! 
보통 유저들이 사용해온 인풋 박스는 내용 기입후 등록(작성)버튼을 누르면 인풋박스가 비워지면서 리스트에 인풋 박스 내용이 기입되는데, 인풋 박스 내용이 그대로 남아있으면 UX적으로 제대로 등록된게 맞는지 혼란이 올것 같습니다! 이렇게되면 사용자가 등록한 내용을 또다시 등록하기 위해서 버튼을 이중으로 누르게 되어 비효율적인 UX 방지를 위해 개선이 필요해 보입니다!

2024-12-03 10:20 UTC, dayaelee commented on src/pages/Review/Review.jsx
> +      alert("리뷰가 등록되었습니다!");
화면 새로고침 로직도 필요해보입니다

만약 현재 페이지에서 리뷰가 5개 이미 등록된 상태에서 사용자가 리뷰를 하나 더 등록할때, 페이지 네이션(페이지 추가 및 페이지 정리)이 이뤄지지 않고 그대로 한 화면에서 하나를 추가하면 6개, 만약 동시에 여러명의 사용자가 리뷰를 등록한다면 한페이지에 5개 이상 n개 씩 등록된 후기가 정리되지 않은 채로 보이게 될 수 있을것 같습니다 
![스크린샷 2024-12-03 오후 7 18 45](https://github.com/user-attachments/assets/bb073240-bd4c-4eb8-bd3a-972db9b7baa2)
![스크린샷 2024-12-03 오후 7 19 31](https://github.com/user-attachments/assets/5ee2d0a0-c9c1-454e-aed8-2ac92b79dea8)

2024-12-03 10:29 UTC, dayaelee approved these changes

2024-12-03 10:29 UTC, dayaelee commented on src/pages/Review/Review.jsx
> +  </div>
해당 부분 css코드관련 해서 프론트 페이지에서 창 크기를 줄였을 때, 박스 안에 있는 요소들이 튀어나와서 반응형 웹 디자인의 기본 원칙을 해치고 있습니다 레이아웃이 깨지면 사이트에 전문성이나 신뢰성이 떨어져 보이기 때문에 페이지 창 크기가 줄더라도 박스의 내용이 박스를 이탈하거나 하지 않도록 개선이 필요해보입니다!

2024-12-03 10:33 UTC, dayaelee requested changes
전체적으로 구현해주시느라 고생하셨습니다! 상기 피드백 드린 부분만 잘 고려하시어 개선해주셨으면 좋겠습니다!

2024-12-04 06:23 UTC, nuyeo requested changes
고생하셨습니다~!

2024-12-04 06:23 UTC, nuyeo commented on src/pages/Review/Review.jsx
> +    }
**1)비로그인 상태라서 리뷰 등록에 실패했을 경우**와 **2)기타 에러로 인해 실패한 경우**의 alert 메시지를 다르게 출력해주어야 할 것 같습니다.

2024-12-04 06:23 UTC, nuyeo commented on src/pages/Review/Review.jsx
> +    <button className="back-button" onClick={() => navigate(-1)}>
서비스 특성 상 뒤로가기 버튼을 누르면 navigate(-1)보다 홈 화면으로 돌아가도록 하는 것이 더 적절해보입니다

2024-12-04 06:58 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +      alert("리뷰가 등록되었습니다!");
해당부분은 일부러 그렇게 해뒀습니다! 리뷰를 등록하자마자 바로 로딩되어버리면 베스트순,평점 높은순,평점 낮은순 으로 봤을 때 방금등록한 리뷰가 뒷페이지로가서 보이지않는 이슈가있습니다

2024-12-04 07:10 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +  </div>
min-width 설정으로 이탈하지않도록 처리했습니다!

2024-12-04 19:41 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +            <button
빈 하트 처리했습니다!

2024-12-04 19:44 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +      alert("리뷰가 등록되었습니다!");
리뷰 등록후 입력필드 비우기 처리했습니다!

2024-12-04 19:47 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +      alert("리뷰가 등록되었습니다!");
만약 동시에 여러명의 사용자가 리뷰를 등록해도 컴포넌트 로딩시 정렬되기때문에 기존리뷰5개+내가작성한리뷰1개 최대 6개까지만 보이게됩니다!

2024-12-04 19:53 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +    }
에러 메시지 다르게 처리했습니다!

2024-12-04 19:54 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +    <button className="back-button" onClick={() => navigate(-1)}>
해당부분 변경했습니다!

2024-12-05 08:42 UTC, dayaelee commented on src/pages/Review/Review.jsx
> +      alert("리뷰가 등록되었습니다!");
아하 그렇군요 한 수 배워갑니다!!!

2024-12-05 08:57 UTC, dayaelee requested changes
완전 고생하셨습니다! 남은 추가 리뷰 부분 확인 부탁드립니다!

2024-12-05 08:57 UTC, dayaelee commented on src/pages/Review/Review.jsx
> +      }
제가 좀 늦게 발견했는데 제가 프로젝트 초반에 design 템플릿에 대해서 말씀드렸었는데 해당 부분 누락이 된 것 같습니다! 리뷰 등록되었다는 메세지 출력시 https://ant.design/components/message

여기있는 메시지 디자인 템플릿 사용하셔서 사이트 전체의 디자인을 통일하는게 어떨까 싶습니다! 

현재 마이페이지 수정 관련 부분은 전부 저 메시지로 처리되어있는 상태입니다 

<img width="867" alt="스크린샷 2024-12-05 오후 5 53 19" src="https://github.com/user-attachments/assets/83fee60d-2a74-4eb2-a325-83f17b8aaba3">

2024-12-05 08:57 UTC, dayaelee commented on src/pages/Review/Review.jsx
> +  </div>
(디스코드로 이야기 된 부분)
아직 그런것으로 확인됩니다,,
아예 내용물 너비를 고정시키고 박스크기 또한 내용물 만큼 고정크기로 해두시면은 차라리 내부 요소(내용) 찌부(찌그러짐)는 없어지고 스크롤로 사용자 입맛에 맞게 볼 수 있게되니 이렇게 처리하시면 어떨까 싶습니다

2024-12-05 09:32 UTC, dayaelee commented
수정사항 확인했습니다 고생하셨습니다!

2024-12-05 09:33 UTC, dayaelee approved these changes
수정사항 확인했습니다 고생하셨습니다!

2024-12-05 09:37 UTC, sall6550 commented on src/pages/Review/Review.jsx
> +      }
처리했습니다!

2024-12-06 06:01 UTC, nuyeo approved these changes
수정사항 확인했습니다. 고생하셨습니다~!

2024-12-06 06:06 UTC, merged