KAN-155  fix: 회원탈퇴 및 로그인 버그 수정 및 안정화
kakaotech-bootcamp-22/fe pull request #17
Opened 2024-12-20 12:35 UTC by dayaelee

### 🔗 관련 이슈
KAN-155 

### 📌 작업 내용

- 회원 정보 수정 완료 바로 안바뀜
-내 프로필 내 정보 row 높이 크기 일정하지 않음
-마이페이지 내 화면 흰색 비율만 늘어나게 수정 (내부 컨텐츠 비율은 고정)
-회원 탈퇴 해도 내 정보 창이 있음
-추가로 회원 탈퇴해도 재가입 절차 없이 바로 로그인
-새로고침 할 때마다 닉네임이 변동 있음
-페이지 이동시 닉네임 변동 있음
-로그인/로그아웃 시 메인페이지가 아닌 현재페이지로 리디렉션 되도록 수정
-카카오 로그인 탈퇴 하고도 갱신이 안됨
-로그아웃하고 다시 로그인 했을때 새로 바꾼걸로 갱신안됨 

### 🧑‍💻 작업 유형
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] CI/CD 변경

### 📷 관련 이미지

### 🚨 주의 사항
배포시에 배포를 위한 .env파일 수정 필요함

### ✅ 체크 리스트
- [ ] 코드 리뷰어가 이해할 수 있도록 주석 및 설명을 추가했습니다.
- [ ] 테스트를 추가하거나 업데이트했습니다.
- [ ] 문서를 업데이트했습니다 (해당 시).
- [ ] 이 변경 사항이 다른 기능에 영향을 미치는지 확인했습니다.

2024-12-22 07:01 UTC, sall6550 approved these changes
고생하셨습니다~

2024-12-24 18:17 UTC, nuyeo approved these changes
<img width="1508" alt="스크린샷 2024-12-25 오전 3 11 32" src="https://github.com/user-attachments/assets/4b5bbc69-4853-479e-890d-aa1bc3694e11" />
로그아웃 or 회원 탈퇴 시 브라우저 콘솔에 GET `/auth/status`  500 에러가 찍히는데 이 부분은 문제 없는 건가요?

2024-12-24 18:22 UTC, nuyeo requested changes
로그아웃 할 때에도 회원 탈퇴처럼 antd message로 '로그아웃이 완료되었습니다.' 문구 나오도록 수정 부탁드립니다

2024-12-26 03:45 UTC, konempty commented on src/components/Home.jsx
> +              if (str.includes("\u00ad")) {
요건 왜 해주는걸까요?

2024-12-26 03:45 UTC, konempty commented on src/components/Navbar/Navbar.jsx
> +            let str = response.data.nickname;
str보다는 좀더 직관적으로 변수명을 지어주세요~!

2024-12-26 03:45 UTC, konempty commented on src/pages/mypage/EditMyPage.styles.js
> +  max-height: 150px;
px로 크기지정하는건 별로 좋은 선택지가 아니예요
[참고](https://brunch.co.kr/@clay1987/170)

2025-03-05 08:40 UTC, merged