KAN-56 메인 페이지 구현
kakaotech-bootcamp-22/fe pull request #2
Opened 2024-10-30 09:04 UTC by nuyeo

### [KAN-56] Title of the Feature/Fix

**Description:**
<img width="1693" alt="스크린샷 2024-10-30 오후 6 01 30" src="https://github.com/user-attachments/assets/146a16e0-2ed5-4ec2-91d2-6a96141a2e02">
- 메인 페이지 구현
- 네이버 블로그 URL 형식에 맞는 링크만 검사 가능하도록 제한

**Type of PR:**
- [x] feat: 새로운 기능 추가
- [ ] fix: 버그 수정
- [ ] refactor: 코드 리팩토링
- [ ] ci-cd: CI/CD 관련 작업
- [ ] docs: 문서 추가 및 수정

**Related Issue:** 
KAN-56

**Checklist:**
- [x] 코드 리뷰어가 이해할 수 있도록 주석 및 설명을 추가했습니다.
- [ ] 테스트를 추가하거나 업데이트했습니다.
- [ ] 문서를 업데이트했습니다 (해당 시).
- [x] 이 변경 사항이 다른 기능에 영향을 미치는지 확인했습니다.

**Additional Context:**

2024-10-30 12:36 UTC, sall6550 approved these changes
고생하셨습니다~~

2024-10-30 12:48 UTC, dayaelee requested changes

2024-10-30 12:48 UTC, dayaelee commented on src/components/Home.jsx
> +        />
피그마 기준으로, 인풋 박스 안에 x버튼(작성 내용 한번에 지우기 기능)이 누락된 것 같아요!

2024-10-30 12:48 UTC, dayaelee commented on src/components/Home.css
> +
UI 비율은 적절해보입니다! 고생하셨습니다!

2024-10-31 01:30 UTC, merged

2024-10-31 01:30 UTC, nuyeo commented on src/components/Home.jsx
> +        />
감사합니다 해당 내용 추가했습니다!