Kan 54 카카오 로그인 페이지 구현
kakaotech-bootcamp-22/fe pull request #5
Opened 2024-11-06 11:17 UTC by dayaelee

### 🔗 관련 이슈

### 📌 작업 내용
이 PR에서 추가된 기능 또는 수정 사항에 대해 간략히 설명해주세요.

- 구현한 기능 1
- 구현한 기능 2 ...

### 🧑‍💻 작업 유형
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] CI/CD 변경

### 📷 관련 이미지
<img width="953" alt="스크린샷 2024-11-06 오후 8 17 07" src="https://github.com/user-attachments/assets/e1e05d6b-f54b-4b4b-817d-e0d984577608">

### 🚨 주의 사항
추후 jwt 테스트를 위해 필요한 코드는 주석처리 해두었습니다.

### ✅ 체크 리스트
- [ ] 코드 리뷰어가 이해할 수 있도록 주석 및 설명을 추가했습니다.
- [ ] 테스트를 추가하거나 업데이트했습니다.
- [ ] 문서를 업데이트했습니다 (해당 시).
- [ ] 이 변경 사항이 다른 기능에 영향을 미치는지 확인했습니다.

2024-11-06 12:29 UTC, sall6550 approved these changes
고생하셨습니다~

2024-11-07 12:16 UTC, nuyeo requested changes

2024-11-07 12:16 UTC, nuyeo commented on src/pages/login/LoginPage.jsx
> +`;
css 파일 분리 부탁드려요

2024-11-07 12:16 UTC, nuyeo commented on src/pages/login/LoginPage.jsx
> +                        <img src={kakaologinImage} />
카카오 로그인 버튼과 구글 로그인 버튼 크기가 다른 것 같습니다! 양쪽 간격을 같게 설정해주세요

2024-11-07 12:21 UTC, dayaelee commented on src/pages/login/LoginPage.jsx
> +`;
해결했습니다!

2024-11-07 12:23 UTC, dayaelee commented on src/pages/login/LoginPage.jsx
> +                        <img src={kakaologinImage} />
와!! 6px 차이를 발견하셨어요 매의눈!! 감사합니다! 해결했습니다!

2024-11-08 08:43 UTC, nuyeo approved these changes
고생하셨습니다~

2024-11-08 08:43 UTC, merged