Kan 55 마이 페이지 구현
kakaotech-bootcamp-22/fe pull request #6
Opened 2024-11-06 13:11 UTC by dayaelee

### 🔗 관련 이슈
Kan 55

### 📌 작업 내용
이 PR에서 추가된 기능 또는 수정 사항에 대해 간략히 설명해주세요.

- 마이 페이지 구현

### 🧑‍💻 작업 유형
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] CI/CD 변경

### 📷 관련 이미지
<img width="840" alt="스크린샷 2024-11-06 오후 10 10 17" src="https://github.com/user-attachments/assets/eb79664c-a602-41e2-a341-3da9bde96c74">

### 🚨 주의 사항
추후에 카카오 계정 연동후 프로필을 불러오는 기능을 추가해야 합니다.

### ✅ 체크 리스트
- [ ] 코드 리뷰어가 이해할 수 있도록 주석 및 설명을 추가했습니다.
- [ ] 테스트를 추가하거나 업데이트했습니다.
- [ ] 문서를 업데이트했습니다 (해당 시).
- [ ] 이 변경 사항이 다른 기능에 영향을 미치는지 확인했습니다.

2024-11-07 09:04 UTC, nuyeo requested changes
백엔드에서 나중에 넘겨받을 값들은 각 페이지 코드에 직접 하드코딩 하는 것보다 미리 로직 만들어두고 받는 변수들에서 값 설정해두는 것이 추후 리팩토링에 용이할 것 같습니다!

2024-11-07 09:04 UTC, nuyeo commented on src/pages/mypage/MyPage.jsx
> +                        <InfoBoxCount>13개</InfoBoxCount>
ex. 13개 에서 '13'은 백엔드에서 받아오고, '개'는 항상 보여주는 값이라 다르게 처리해줘야 할 것 같아요
그리고 피그마 상에서 숫자 폰트 크기가 더 크고 볼드 처리 되어 있고, '개'는 일반 폰트로 작성되어 있어서 맞춰서 수정 부탁드립니다

2024-11-07 09:04 UTC, nuyeo commented on src/pages/mypage/MyPage.jsx
> +                <FooterButton>회원탈퇴</FooterButton>
회원탈퇴 버튼 가운데 정렬 맞춰주세요!

2024-11-07 12:07 UTC, dayaelee commented on src/pages/mypage/MyPage.jsx
> +                        <InfoBoxCount>13개</InfoBoxCount>
완료 했습니다!

2024-11-07 12:17 UTC, dayaelee commented on src/pages/mypage/MyPage.jsx
> +                <FooterButton>회원탈퇴</FooterButton>
완료했습니다!

2024-11-07 12:30 UTC, sall6550 approved these changes
고생하셨습니다~~

2024-11-09 04:45 UTC, nuyeo approved these changes
고생하셨습니다~

2024-11-09 04:45 UTC, nuyeo commented on src/pages/mypage/EditMyPage.styles.js
나중에 가능하시면 css로 style 파일 통합 부탁드립니다~!

2024-11-09 05:27 UTC, dayaelee commented on src/pages/mypage/EditMyPage.styles.js
넵!!!

2024-11-09 05:57 UTC, merged